-- =========================================================
-- V1 初期スキーマ (PostgreSQL / prod)
-- 方言差: 自動採番は IDENTITY 列。SQLite 版は db/migration/sqlite/V1__init.sql。
-- ※本ファイルは prod 用。dev(SQLite) では読み込まれない({vendor} で切替)。
-- =========================================================

-- 避難所
CREATE TABLE shelters (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_ja     VARCHAR(255)     NOT NULL,
    name_en     VARCHAR(255),
    name_zh     VARCHAR(255),
    address     VARCHAR(512),
    lat         DOUBLE PRECISION NOT NULL,
    lng         DOUBLE PRECISION NOT NULL,
    capacity    INTEGER,
    facilities  TEXT,
    created_at  TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 開発/初期投入用サンプルデータ（※実在の避難所情報ではない）
INSERT INTO shelters (name_ja, name_en, name_zh, address, lat, lng, capacity, facilities) VALUES
 ('サンプル第一小学校 避難所', 'Sample No.1 Elementary School Shelter', '样例第一小学避难所', '京都市中京区サンプル町1-1', 35.01160, 135.76810, 300, '飲料水,毛布,AED'),
 ('サンプル中央公民館 避難所', 'Sample Central Community Hall Shelter', '样例中央公民馆避难所', '京都市下京区サンプル町2-2', 34.98530, 135.75850, 200, '飲料水,簡易トイレ'),
 ('サンプル総合体育館 避難所', 'Sample Gymnasium Shelter', '样例综合体育馆避难所', '京都市左京区サンプル町3-3', 35.02670, 135.78230, 500, '飲料水,毛布,AED,医療スペース');
