-- =========================================================
-- V2 AI 問答ログ (PostgreSQL / prod)
-- =========================================================
CREATE TABLE chat_logs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question   TEXT        NOT NULL,
    answer     TEXT        NOT NULL,
    lang       VARCHAR(16) NOT NULL,
    sources    TEXT,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
