-- =========================================================
-- V5 危険区域 hazard_zones (PostgreSQL / prod)
-- 区域几何は GeoJSON 文字列で保持（PostGIS 非依存・双库共通）。
-- =========================================================
CREATE TABLE hazard_zones (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type             VARCHAR(32)  NOT NULL,
    severity         VARCHAR(16)  NOT NULL,
    name_ja          VARCHAR(255) NOT NULL,
    name_en          VARCHAR(255),
    name_zh          VARCHAR(255),
    description      TEXT,
    geojson          TEXT         NOT NULL,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(64),
    last_modified_at TIMESTAMP,
    last_modified_by VARCHAR(64)
);

INSERT INTO hazard_zones (type, severity, name_ja, name_en, name_zh, description, geojson, created_by, last_modified_by) VALUES
 ('FLOOD', 'HIGH', 'サンプル浸水想定区域', 'Sample Flood Zone', '样例浸水区域', '大雨時の浸水想定（サンプル）',
  '{"type":"Polygon","coordinates":[[[135.760,35.005],[135.775,35.005],[135.775,35.015],[135.760,35.015],[135.760,35.005]]]}',
  'system', 'system'),
 ('LANDSLIDE', 'MEDIUM', 'サンプル土砂災害警戒区域', 'Sample Landslide Zone', '样例土砂灾害区域', '土砂崩れ警戒（サンプル）',
  '{"type":"Polygon","coordinates":[[[135.778,35.025],[135.788,35.025],[135.788,35.033],[135.778,35.033],[135.778,35.025]]]}',
  'system', 'system');

UPDATE hazard_zones SET last_modified_at = created_at;
